apiVersion: apps/v1
kind: Deployment
metadata:
  name: autentication
  labels:
    app: autentication
spec:
  replicas: 1
  template:
    metadata:
      name: autentication
      labels:
        app: autentication
    spec:
      containers:
        - name: autentication
          image: mrsimonty/autentication:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8095
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: autentication