apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverconfig
  labels:
    app: serverconfig
spec:
  replicas: 1
  template:
    metadata:
      name: serverconfig
      labels:
        app: serverconfig
    spec:
      containers:
        - name: serverconfig
          image: mrsimonty/configserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: serverconfig