apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    app: configserver
spec:
  replicas: 1
  template:
    metadata:
      name: configserver
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: mrsimonty/configserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: configserver