apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumno
  labels:
    app: alumno
spec:
  replicas: 1
  template:
    metadata:
      name: alumno
      labels:
        app: alumno
    spec:
      containers:
        - name: alumno
          image: mrsimonty/alumno:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: alumno