apiVersion: apps/v1
kind: Deployment
metadata:
  name: curso
  labels:
    app: curso
spec:
  replicas: 1
  template:
    metadata:
      name: curso
      labels:
        app: curso
    spec:
      containers:
        - name: curso
          image: mrsimonty/curso:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: curso